export const MW=Object.freeze({NaOH:39.997,KOH:56.106,citricAnhydrous:192.12,citricMonohydrate:210.14,lactic:90.08,acetic:60.052});
export const ACID_MODELS=Object.freeze({citric_anhydrous:{label:'Citric acid (anhydrous)',mw:MW.citricAnhydrous,equivalents:3},citric_monohydrate:{label:'Citric acid (monohydrate)',mw:MW.citricMonohydrate,equivalents:3},lactic:{label:'Lactic acid',mw:MW.lactic,equivalents:1},acetic:{label:'Acetic acid',mw:MW.acetic,equivalents:1}});
const FA_KEYS=['lauric','myristic','palmitic','stearic','ricinoleic','oleic','linoleic','linolenic'];
const sum=a=>a.reduce((x,y)=>x+y,0); const close=(a,b,t=1e-9)=>Math.abs(a-b)<=t;
export const ratioToConcentration=r=>{if(!(r>=1))throw Error('Water:lye ratio must be at least 1.00 in Bel Lei\'s standard mode.');return 1/(1+r)};
export const concentrationToRatio=c=>{if(!(c>0&&c<=.5))throw Error('Lye concentration must be greater than 0 and no more than 50% in standard mode.');return(1-c)/c};
export function acidFactor(k,a='NaOH'){const m=ACID_MODELS[k];if(!m)throw Error(`Unknown acid model: ${k}`);return m.equivalents*MW[a]/m.mw}
export function acidNeutralization({acidKey,productMass,activeFraction=1,alkali='NaOH'}){if(!(productMass>=0))throw Error('Acid product mass must be nonnegative.');if(!(activeFraction>=0&&activeFraction<=1))throw Error('Acid active fraction must be 0-1.');return productMass*activeFraction*acidFactor(acidKey,alkali)}
export function validateRecipeInput(i){const errors=[],warnings=[];if(!Array.isArray(i.oils)||!i.oils.length)errors.push({code:'NO_OILS',message:'Add at least one oil or fat.'});const t=sum((i.oils||[]).map(o=>Number(o.percent)||0));if(!close(t,100,1e-6))errors.push({code:'OIL_PERCENT_TOTAL',message:`Oil percentages total ${t.toFixed(2)}%; they must total 100%.`});if(!(i.totalOilWeight>0))errors.push({code:'OIL_WEIGHT',message:'Total oil weight must be greater than 0.'});for(const o of i.oils||[]){if(!(o.naohSap>0))errors.push({code:'MISSING_SAP',message:`${o.name||'Oil'} does not have a locked working NaOH SAP.`});if(!(o.kohSap>0))errors.push({code:'MISSING_KOH_SAP',message:`${o.name||'Oil'} does not have a locked working KOH SAP.`});if(o.status&&o.status!=='WORKING VALUE')warnings.push({code:'SPECIAL_LIPID',message:`${o.name}: ${o.status}. Verify the material before production.`})}if(!(i.superfatPct>-25&&i.superfatPct<100))errors.push({code:'SUPERFAT_RANGE',message:'Superfat value is outside supported bounds.'});if(i.superfatPct<0)warnings.push({code:'NEGATIVE_SUPERFAT',message:'Negative superfat means intentional alkali excess.'});for(const[k,v]of[['NaOH purity',i.naohPurity],['KOH purity',i.kohPurity]]){if(!(v>0&&v<=1))errors.push({code:'PURITY',message:`${k} must be an active fraction above 0 and no more than 1.`});else if(v<.8)warnings.push({code:'LOW_PURITY',message:`${k} is below 80%; verify the source or purity test.`})}if(i.lyeType==='dual'&&!close(i.naohEquivalentFraction+i.kohEquivalentFraction,1))errors.push({code:'DUAL_SPLIT',message:'Dual-lye equivalent fractions must sum to 1.000.'});return{errors,warnings}}
function fatty(oils){const out=Object.fromEntries(FA_KEYS.map(k=>[k,0]));let coverage=0;for(const o of oils){const f=o.percent/100;if(o.modelStatus==='Standard'||o.modelStatus==='Special'){coverage+=f;for(const k of FA_KEYS)out[k]+=(o.fattyAcids?.[k]||0)*f}}return{values:out,coverage}}
function props(fa,iodine){return{hardness:fa.lauric+fa.myristic+fa.palmitic+fa.stearic,cleansing:fa.lauric+fa.myristic,bubbly:fa.lauric+fa.myristic+fa.ricinoleic,creamy:fa.palmitic+fa.stearic+fa.ricinoleic,conditioning:fa.oleic+fa.linoleic+fa.linolenic+fa.ricinoleic,longevityTendency:fa.palmitic+fa.stearic,pufa:fa.linoleic+fa.linolenic,iodine}}
export function calculateRecipe(i){const{errors,warnings}=validateRecipeInput(i);if(errors.length)return{ok:false,errors,warnings};const lines=i.oils.map(o=>({...o,weight:i.totalOilWeight*o.percent/100}));const stoichNa=sum(lines.map(o=>o.weight*o.naohSap)),stoichKo=sum(lines.map(o=>o.weight*o.kohSap)),sf=1-i.superfatPct/100;let ne=1,ke=0;if(i.lyeType==='koh'){ne=0;ke=1}else if(i.lyeType==='dual'){ne=i.naohEquivalentFraction;ke=i.kohEquivalentFraction}const sapNa=stoichNa*sf*ne,sapKo=stoichKo*sf*ke;let acidNa=0,acidKo=0;for(const a of i.acids||[]){const n=acidNeutralization({...a,alkali:'NaOH'}),k=acidNeutralization({...a,alkali:'KOH'});if(a.allocation==='naoh')acidNa+=n;else if(a.allocation==='koh')acidKo+=k;else{acidNa+=n*ne;acidKo+=k*ke}}const activeNa=sapNa+acidNa,activeKo=sapKo+acidKo,weighedNa=activeNa/i.naohPurity,weighedKo=activeKo/i.kohPurity,dry=weighedNa+weighedKo;let ratio,conc,water;if(i.waterMode==='ratio'){ratio=i.waterValue;conc=ratioToConcentration(ratio);water=dry*ratio}else if(i.waterMode==='concentration'){conc=i.waterValue;ratio=concentrationToRatio(conc);water=dry*ratio}else if(i.waterMode==='percent'){water=i.totalOilWeight*i.waterValue;ratio=water/dry;conc=1/(1+ratio)}else throw Error('Unsupported water mode');const f=fatty(i.oils);if(f.coverage<.999)warnings.push({code:'FA_INCOMPLETE',message:`Fatty-acid property coverage is ${(f.coverage*100).toFixed(1)}%; one or more selected materials use special/unlocked chemistry.`});const iodine=sum(i.oils.map(o=>(o.iodine??0)*o.percent/100));const properties=props(f.values,iodine);const fragranceMass=(i.fragrancePctOfOils||0)*i.totalOilWeight/100;const additiveMass=sum((i.additives||[]).map(a=>Number(a.mass)||0));const totalBatchWeight=i.totalOilWeight+dry+water+fragranceMass+additiveMass;return{ok:true,errors:[],warnings,oilLines:lines,lye:{stoichNaoh:stoichNa,stoichKoh:stoichKo,sapActiveNaoh:sapNa,sapActiveKoh:sapKo,acidActiveNaoh:acidNa,acidActiveKoh:acidKo,weighedNaoh:weighedNa,weighedKoh:weighedKo,dryAlkali:dry},water:{mass:water,ratio,concentration:conc},fragranceMass,totalBatchWeight,fattyAcids:f.values,faCoverage:f.coverage,properties,audit:[{id:'stoich_naoh',label:'0% SF pure NaOH equivalent',value:stoichNa},{id:'stoich_koh',label:'0% SF pure KOH equivalent',value:stoichKo},{id:'sap_naoh',label:'Active NaOH after superfat/split',value:sapNa},{id:'sap_koh',label:'Active KOH after superfat/split',value:sapKo},{id:'acid_naoh',label:'Acid neutralization active NaOH',value:acidNa},{id:'acid_koh',label:'Acid neutralization active KOH',value:acidKo},{id:'weighed_naoh',label:`NaOH to weigh @ ${(i.naohPurity*100).toFixed(2)}% purity`,value:weighedNa},{id:'weighed_koh',label:`KOH to weigh @ ${(i.kohPurity*100).toFixed(2)}% purity`,value:weighedKo},{id:'water',label:`Water @ ${(conc*100).toFixed(2)}% concentration (${ratio.toFixed(3)}:1)`,value:water}]}}
export const roundForDisplay=(v,d=2)=>Number(v.toFixed(d));
export function moldVolume(shape,d){const n=x=>Number(x)||0;if(shape==='rect')return n(d.length)*n(d.width)*n(d.height);if(shape==='round')return Math.PI*(n(d.diameter)/2)**2*n(d.height);if(shape==='ellipse')return Math.PI*(n(d.length)/2)*(n(d.width)/2)*n(d.height);if(shape==='triangle')return .5*n(d.base)*n(d.triangleHeight)*n(d.length);if(shape==='roundFrustum'){const r1=n(d.bottomDiameter)/2,r2=n(d.topDiameter)/2,h=n(d.height);return Math.PI*h/3*(r1*r1+r1*r2+r2*r2)}return null}
export const INCH_TO_CM=2.54,CUBIC_INCH_TO_ML=16.387064;
function moldUnitFactor(fromUnit,toUnit){if(!['in','cm'].includes(fromUnit)||!['in','cm'].includes(toUnit))throw Error('Mold dimension unit must be inches or centimeters.');if(fromUnit===toUnit)return 1;return fromUnit==='in'?INCH_TO_CM:1/INCH_TO_CM}
export function convertMoldDimensions(dimensions,fromUnit,toUnit){const factor=moldUnitFactor(fromUnit,toUnit);return Object.fromEntries(Object.entries(dimensions).map(([key,value])=>[key,(Number(value)||0)*factor]))}
export function moldVolumeMl(shape,dimensions,unit='cm'){const volume=moldVolume(shape,dimensions);if(volume===null)return null;moldUnitFactor(unit,unit);return unit==='in'?volume*CUBIC_INCH_TO_ML:volume}
export function moldWorkingVolume({shape,dimensions,unit='cm',waterFillMl=0}){const geometricVolume=moldVolume(shape,dimensions),geometricVolumeMl=moldVolumeMl(shape,dimensions,unit),calibration=Number(waterFillMl)||0;return{geometricVolume,geometricVolumeMl,workingVolumeMl:calibration>0?calibration:geometricVolumeMl||0,source:calibration>0?'water-fill':'geometry'}}
export function costing({materials=0,packaging=0,labor=0,manufacturingOverhead=0,sellableUnits=1,price=0,channelFees=0}){const batch=materials+packaging+labor+manufacturingOverhead,unit=batch/Math.max(1,sellableUnits),net=price-channelFees,profit=net-unit;return{batchCost:batch,costPerSellableUnit:unit,netRevenue:net,profitPerUnit:profit,marginPct:net?profit/net*100:null,markupPct:unit?(price-unit)/unit*100:null}}
