name: Build and Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files (before unzip)
        run: ls -la

      - name: Ensure unzip + extract
        run: |
          sudo apt-get update && sudo apt-get install -y unzip
          # 👇 If your ZIP has a different name, change it here
          unzip -o soap-calc-pro-starter.zip

      - name: List files (after unzip)
        run: |
          ls -la
          echo "----"
          find . -maxdepth 2 -type d -print

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      # Patch asset paths so GitHub Pages serves correctly under /belleis-soap-calculator/
      - name: Patch base paths
        run: |
          sed -i
